title: Form Field
status: "ready"
collated: true
context:
  label:
    value: "Input label"
    show: true
variants:
  - name: default
    context:
      label:
        for: "default"
      input:
        for: "default"
  - name: icon
    context:
      input-icon:
        icon: "visibility"
      formField:
        modifier: "inv-form-field--icon"
      label:
        for: "icon"
      input:
        for: "icon"
  - name: progress
    context:
      input-icon:
        icon: "visibility"
      formField:
        modifier: "inv-form-field--icon inv-form-field--progress"
      label:
        for: "progress"
      input:
        for: "progress"
        progress: true
      form-text:
        value: "Cara, nunca vi uma senha menos segura."
        modifier: "inv-form-text--error"
      inputProgress:
        value: 15
        modifier: "inv-input-progress--invalid"
  - name: error
    context:
      label:
        posfix: "- obrigatório"
        for: "error"
      input:
        modifier: "inv-input--error"
        for: "error"
      form-text:
        value: "Cara, nunca vi uma senha menos segura."
        modifier: "inv-form-text--error"
  - name: disabled
    context:
      disabled: true
      label:
        posfix: "- desabilitado"
        modifier: "inv-label--disabled"
