title: Menu Search
status: "wip"
preview: "@preview-menu-search"
collated: true
context:
  icon: search
  input:
    placeholder: " "
    for: "my-input-search"
variants:
  - name: open
    context:
      input:
        placeholder: "Ctrl+k para buscar"
      menu-search:
        modifier: "inv-menu-search--open"
