title: Menu Search
status: "wip"
preview: "@preview-menu"
context:
  preview:
    styles: "
      background-color: var(--color-system--dark);
      display: flex;
      justify-content: center;
      align-items: center;
      flex-direction: column;
      height: 50%;
      width: 100%;
      border-radius: 10px;
    "
  icon: search
  input:
    placeholder: "Ctrl+k para buscar"
    for: "my-input-search"
variants:
  - name: open
    context:
      menu-search:
        modifier: "inv-menu-search--open"
