title: Input
status: "ready"
collated: true
variants:
  - name: default
  - name: disabled
    context:
      disabled: true
  - name: error
    context:
      input:
        modifier: "inv-input--error"
