language: node_js
node_js:
  "node"
addons:
  chrome: stable
install:
  - npm install
stages:
  - test
  - name: browser
    if: type = push
jobs:
  include:
    - stage: browser
      script: cd test/visual && backstop approve
      script: cd test/visual && rm -rf backstop_data/bitmaps_test && backstop test
cache:
  directories:
    - node_modules
