language: node_js
node_js:
  "node"
addons:
  chrome: stable
install:
  - npm install
stages:
  - test
  - name: browser
    if: type = push
jobs:
  include:
    - stage: browser
      script: npm run test:visual:approve
      script: npm run test:visual
cache:
  directories:
    - node_modules
