title: Menu
status: "wip"
preview: "@preview-menu"
collated: false
variants:
  - name: default
    context:
      menu:
        open: false
  - name: open
    context:
      menu:
        open: true
  - name: logo
    context:
      menu-logo:
        src: /assets/images/logo.png
      menu:
        open: false
        search: false
  - name: logo-full
    context:
      menu-logo:
        src: /assets/images/logo_full.png
        modifier: inv-menu-logo--open
      menu:
        open: true
        logo: true
        search: false
  - name: search
    context:
      icon: search
      formField:
        modifier: "inv-menu__search"
      input:
        placeholder: " "
      menu:
        open: false
        logo: true
        search: true
  - name: search-full
    context:
      icon: search
      formField:
        modifier: "inv-menu__search inv-menu__search--open"
      input:
        placeholder: "Ctrl+k para buscar"
      menu:
        open: true
        logo: true
        search: true
  - name: brand-logo
    context:
      icon: search
      formField:
        modifier: "inv-menu__search"
      input:
        placeholder: " "
      menu:
        open: false
        logo: true
        brand-logo: true
        search: true
  - name: brand-logo-full
    context:
      icon: search
      formField:
        modifier: "inv-menu__search inv-menu__search--open"
      input:
        placeholder: "Ctrl+k para buscar"
      menu:
        open: true
        logo: true
        brand-logo: true
        search: true
  - name: Menu List
    context:
      icon: search
      formField:
        modifier: "inv-menu__search"
      input:
        placeholder: " "
      label:
        value: "Ctrl+k"
        modifier: "inv-menu__search-label"
      menu:
        open: false
        logo: true
        brand-logo: true
        search: true
        list:
          - item:
              value: wifi
              title: " "
          - item:
              value: face
              title: " "
  - name: Menu List Full
    context:
      icon: search
      formField:
        modifier: "inv-menu__search inv-menu__search--open"
      input:
        placeholder: "Ctrl+k para buscar"
      menu:
        open: true
        logo: true
        brand-logo: true
        search: true
        list:
          - item:
              value: wifi
              title: "Oi"
          - item:
              value: face
              title: " "
