title: Menu
status: "wip"
preview: "@preview-menu"
collated: false
variants:
  - name: default
    context:
      menu:
        open: false
  - name: open
    context:
      menu:
        open: true
  - name: logo
    context:
      menu:
        open: false
        logo: true
        search: false
  - name: logo-full
    context:
      menu:
        open: true
        logo: true
        search: false
  - name: search
    context:
      icon: search
      formField:
        modifier: "inv-menu__search"
      input:
        placeholder: " "
      menu:
        open: false
        logo: true
        search: true
  - name: search-full
    context:
      icon: search
      formField:
        modifier: "inv-menu__search inv-menu__search--open"
      input:
        placeholder: "Ctrl+k para buscar"
      menu:
        open: true
        logo: true
        search: true
  - name: brand-logo
    context:
      icon: search
      formField:
        modifier: "inv-menu__search"
      input:
        placeholder: " "
      menu:
        open: false
        logo: true
        brand-logo: true
        search: true
  - name: brand-logo-full
    context:
      icon: search
      formField:
        modifier: "inv-menu__search inv-menu__search--open"
      input:
        placeholder: "Ctrl+k para buscar"
      menu:
        open: true
        logo: true
        brand-logo: true
        search: true
  - name: Menu List
    context:
      icon: search
      formField:
        modifier: "inv-menu__search"
      input:
        placeholder: " "
      label:
        value: "Ctrl+k"
        modifier: "inv-menu__search-label"
      menu:
        open: false
        logo: true
        brand-logo: true
        search: true
        list: true
