title: Menu
status: "wip"
preview: "@preview-menu"
collated: false
context:
  menu-logo:
    src: /assets/images/logo.png
  menu-logo-brand:
    src: /assets/images/brand-logo.png
variants:
  - name: default
  - name: open
    context:
      menu:
        open: true
        logo: false
        search: false
  - name: logo
    context:
      menu:
        open: false
        logo: true
        search: false
  - name: logo-full
    context:
      menu-logo:
        src: /assets/images/logo_full.png
        modifier: inv-menu-logo--open
      menu:
        open: true
        logo: true
        search: false
  - name: search
    context:
      menu:
        open: false
        logo: true
        search: true
  - name: search-full
    context:
      menu-logo:
        src: /assets/images/logo_full.png
        modifier: inv-menu-logo--open
      menu:
        open: true
        logo: true
        search: true
  - name: brand-logo
    context:
      menu:
        open: false
        logo: true
        brand: true
        search: true
  - name: brand-logo-full
    context:
      menu-logo:
        src: /assets/images/logo_full.png
        modifier: inv-menu-logo--open
      menu-logo-brand:
        modifier: inv-menu-logo-brand--open
      menu:
        open: true
        logo: true
        brand: true
        search: true
  - name: Menu List
    context:
      menu:
        open: false
        logo: true
        brand: true
        search: true
        list:
          - item:
              value: wifi
              title: " "
          - item:
              value: face
              title: " "
  - name: Menu List Full
    context:
      menu-logo:
        src: /assets/images/logo_full.png
        modifier: inv-menu-logo--open
      menu-logo-brand:
        modifier: inv-menu-logo-brand--open
      menu:
        open: true
        logo: true
        brand: true
        search: true
        list:
          - item:
              value: wifi
              title: "Oi"
              modifier: "inv-menu__list-item--open"
          - item:
              value: face
              title: " "
              modifier: "inv-menu__list-item--open"
