title: Menu
status: "wip"
preview: "@preview-menu"
context:
  preview:
    styles: "
      height: 100%;
    "
  menu-logo:
    src: /assets/images/logo.png
    alt: Menu Logo
  menu-logo-open:
    src: /assets/images/logo-full.png
    alt: Menu Logo
  menu-brand:
    src: /assets/images/brand.png
  menu-brand-open:
    src: /assets/images/brand-full.png
  icon: search
  input:
    placeholder: "Ctrl+k para buscar"
  menu-search:
    modifier: "inv-menu-search--open"
  menu-list:
    modifier: inv-menu-list--open
    list:
      - item:
          icon: wifi
          text: Profile
      - item:
          icon: face
          text: Pontos de Venda
      - item:
          icon: search
          text: Métricas
      - item:
          icon: people
          text: Acessos Externos
variants:
  - name: default
  - name: visible
    context:
      menu:
        modifier: inv-menu--visible
