title: Tip
status: "wip"
collated: true
preview: "@preview-tip"
context:
  tip:
    modifier: "inv-tip--bottom-left"
    text: "Valida o IMEI ao realizar o login pelo celular. O sistema irá permitir que o usuário acesse o sistema através de um celular com o IMEI diferente do especificado. Essa validação só será realizada caso tenha sido configurada nas permissões do Perfil de Acesso. Para permitir que o usuário acesse de outro aparelho basta limpar o campo."
variants:
  - name: bottom-right
    context:
      tip:
        modifier: "inv-tip--bottom-right"
  - name: top-right
    context:
      tip:
        modifier: "inv-tip--top-right"
  - name: top-left
    context:
      tip:
        modifier: "inv-tip--top-left"
