title: List
status: "ready"
collated: true
display:
context:
  list:
    - "#1 Opção"
    - "#2 Opção"
    - "#3 Opção"
    - "#4 Opção"
    - "#5 Opção"
    - "#6 Opção"
    - "#7 Opção"
    - "#8 Opção"
variants:
  - name: default
  - name: multiselect
    context:
      checkbox: "@checkbox"
      multiselect: true

