title: Input Addon
status: "ready"
collated: true
variants:
  - name: default
  - name: disabled
    context:
      disabled: true
      clear-input:
        disabled: true
  - name: icon
    context:
      input-icon:
        icon: "visibility"
      inputAddon:
        modifier: "inv-input-addon__input--icon"
