title: Label
status: "ready"
collated: true
variants:
  - name: default
    context:
      value: "Input label"
  - name: required
    context:
      value: "Nome"
      posfix: "- obrigatório"
  - name: disable
    context:
      value: "Senha Genérica"
      posfix: "- desabilitado"
      modifier: "inv-label--disabled"
