title: Label
status: "ready"
collated: true
variants:
  - name: default
    context:
      label:
        value: "Input label"
  - name: required
    context:
      label:
        value: "Nome"
        posfix: "- obrigatório"
  - name: disable
    context:
      label:
        value: "Senha Genérica"
        posfix: "- desabilitado"
        modifier: "inv-label--disabled"
