title: Menu List
status: "wip"
preview: "@preview-menu"
context:
  preview:
    styles: "
      padding: 0;
      background-color: #1d2e44;
      border-radius: 0;
    "
  menu-list:
    list:
      - item:
          icon: wifi
          text: Profile
      - item:
          icon: face
          text: Pontos de Venda
      - item:
          icon: search
          text: Métricas
      - item:
          icon: people
          text: Acessos Externos
variants:
  - name: default
  - name: open
    context:
      menu-list:
        modifier: inv-menu-list--open
