title: Input Icon
status: "ready"
collated: true
variants:
  - name: default
    context:
      input-icon:
        icon: "event"
  - name: active
    context:
      input-icon:
        icon: "visibility"
        modifier: "inv-input-icon--active"
  - name: disable
    context:
      input-icon:
        icon: "visibility"
        disabled: true
        modifier: "inv-input-icon--disabled"
