title: Menu Logo
status: "wip"
collated: true
context:
  menu-logo:
    src: /images/logo.jpg
    alt: Menu Logo
variants:
  - name: default
  - name: open
    context:
      menu-logo:
        modifier: inv-menu-logo--open
      