title: Input File
status: "wip"
collated: true
preview: "@preview"
context:
  label:
    value: "Input label"
    posfix: "- obrigatório"
    for: "error"
  input-file:
    button-text: Enviar arquivo
  clear-input:
    disabled: true
variants:
  - name: default
  - name: active
    context:
      input-file:
        text:
          modifier: inv-input-file__text--active
  - name: file-name
    context:
      input-file:
        modifier: inv-input-file--selected
      clear-input:
        disabled: false
  - name: disabled
    context:
      input-file:
        text:
          modifier: inv-input-file__text--disabled
        icon:
          modifier: inv-input-file-icon--disabled
  #   context:
  #     clear-input:
  #       disabled: true
  # - name: file-selected
  # - name: input-file-disabled
  #   context:
  #     input-file:
  #       modifier: inv-input-file__btn--disabled
  #       disabled: true
  #     clear-input:
  #       disabled: true
  #     label:
  #       modifier: "inv-label--disabled"
  # - name: input-file-required
  #   context:
  #     input-file:
  #       modifier: inv-input-file__btn--required
  #     clear-input:
  #       disabled: true
  # - name: input-file-error
  #   context:
  #     input-file:
  #       modifier: inv-input-file__btn--error
  #       button-text: visitas.txt
  #     form-text:
  #       value: "Cara, nunca vi uma senha menos segura."
  #       modifier: "inv-form-text--error"

