title: Input File
status: "wip"
collated: true
preview: "@preview"
context:
  input-file:
    placeholder: Enviar arquivo
  clear-input:
    disabled: true
variants:
  - name: default
  - name: active
    context:
      input-file:
        text:
          modifier: inv-input-file__text--active
  - name: file-name
    context:
      input-file:
        modifier: inv-input-file--selected
        placeholder: file.txt
      clear-input:
        disabled: false
  - name: disabled
    context:
      input-file:
        modifier: inv-input-file--disabled
        text:
          modifier: inv-input-file__text--disabled
        icon:
          modifier: inv-input-file-icon--disabled
        input:
          disabled: true
  - name: error
    context:
      input-file:
        modifier: inv-input-file--error
        text:
          modifier: inv-input-file__text--error
  - name: error-uploaded
    context:
      input-file:
        modifier: inv-input-file--selected inv-input-file--error
        placeholder: file.txt
        text:
          modifier: inv-input-file__text--error
      clear-input:
        disabled: false
  - name: error-active
    context:
      input-file:
        modifier: inv-input-file--selected inv-input-file--error
        placeholder: file.txt
        text:
          modifier: inv-input-file__text--error inv-input-file__text--error-active
      clear-input:
        disabled: false
