title: Form Text
status: "ready"
collated: true
variants:
  - name: default
    context:
      value: "Texto de ajuda para o campo"
  - name: error
    context:
      value: "Cara, nunca vi uma senha menos segura."
      modifier: "inv-form-text--error"
  - name: success
    context:
      value: "Senha segura"
      modifier: "inv-form-text--success"
