title: Form Text
status: "ready"
collated: true
variants:
  - name: default
    context:
      form-text:
        value: "Texto de ajuda para o campo"
  - name: error
    context:
      form-text:
        value: "Cara, nunca vi uma senha menos segura."
        modifier: "inv-form-text--error"
  - name: success
    context:
      form-text:
        value: "Senha segura"
        modifier: "inv-form-text--success"
  - name: alert
    context:
      form-text:
        value: "Senha segura"
        modifier: "inv-form-text--alert"
