title: Menu Brand Logo
status: "wip"
collated: true
context:
  menu-brand-logo:
    src: /assets/images/brand-logo.png
    alt: Menu Brand Logo
variants:
  - name: default
  - name: open
    context:
      menu-brand-logo:
        modifier: inv-menu-brand-logo--open